@startuml
hide empty field
hide empty  method


abstract class Printer
abstract class PluginPrinterTemplate
abstract class OSPrinter
abstract class OSSerializedPrinter
class OSColoredPrinter

class PrinterRouter


Printer <|-- ColoredPrinter
OSPrinter <|-- OSColoredPrinter
ColoredPrinter <|-- OSColoredPrinter
OSPrinter <|-- OSSerializedPrinter
OSSerializedPrinter <|-- OSJSONPrinter
PluginPrinterTemplate <|-- PrinterRouter
PrinterRouter <|.. OSColoredPrinter
PrinterRouter <|.. OSJSONPrinter
@enduml
