---
name: "Cibyl CI - Check"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.6', '3.9' ]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-extra
      - name: "Run tox"
        run: PYTHONWARNINGS="ignore" TOX_PARALLEL_NO_SPINNER=1 tox -p
