---
name: "Cibyl CI - Gate"
on:
  pull_request_review:
    types: [ submitted ]

jobs:
  gate:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.6', '3.9' ]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-extra
      - name: "Run integration tests"
        run: tox -e intr
      # - name: "Run e2e tests"
      #   run: tox -e e2e
