---
name: "Cibyl CI"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.9' ]
    steps:
      - name: "Install SSH key"
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.RHOS_INFRA_PRIVATE_KEY }}
      - name: "Checkout repo"
        uses: actions/checkout@v1
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run End-To-End tests"
        run: tox -e e2e
