---
name: "Publish Cibyl to PyPI"
on:
  push:
    tags:
      # asterisk allow matching tags like v1.0.0.rc1, etc.
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6']
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v1
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install pypa/build"
        run: |
          python -m pip install build
      - name: "Build a wheel and source distribution"
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: "Publish package to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: "Publish package to TestPyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
